import React from "react";
import Header from "../ui/Header";
import Navigation from "../ui/Navigation";
import AppTemplate from "../ui/AppTemplate";
import { Link } from "react-router-dom";

import appLogo from "../../img/comfortmattetemperud.jpg";
export default function LipResults() {
   return (
      <AppTemplate>
         <Header />
         <Navigation />
         <h2>Results</h2>
         <div className="mb-5"></div>
         <h3>Give your Lips the personality they deserve!</h3>
         <h4>
            These are your personalized lip matches.The buy now buttons will
            instantly take you to purchase your personalized lip color.You can
            save each look by clicking save below.
         </h4>

         <div className="card bg-light mb-3" style={{ maxWidth: "18rem" }} />
         <div className="card-header">Match</div>
         <div className="card-body">
            <img
               src={appLogo}
               width="46px;"
               alt="Lip Service Lips"
               className="mb-1 ml-2"
            />
            <h4 id="cardfontcolor"> Name:Hitch Hike</h4>
            <h4 id="cardfontcolor"> Finish: Comfort Matte</h4>
            <h4 id="cardfontcolor"> Brand: Urban Decay</h4>
            <a
               href="https://www.urbandecay.com/vice-lipstick-by-urban-decay/ud771.html"
               className="btn btn-primary float-right btn-sm"
            >
               Buy Now
            </a>
            <h5 className="card-title">Light card title</h5>
            <p className="card-text" id="cardfontcolor">
               {" "}
               These are your personalized lip matches.The buy now buttons that
               are provided above will instantly take you to purchase your
               personalized lip color.You can save each look generated by
               pressing the save below.
            </p>
         </div>
         <div className="mb-8"></div>
         <div className="card bg-light mb-3" style={{ maxWidth: "18rem" }} />
         <div className="card-header">Match</div>
         <div className="card-body">
            <img
               src={appLogo}
               width="46px;"
               alt="Lip Service Lips"
               className="mb-1 ml-2"
            />
            <h4 id="cardfontcolor"> Name:Hitch Hike</h4>
            <h4 id="cardfontcolor"> Finish: Comfort Matte</h4>
            <h4 id="cardfontcolor"> Brand: Urban Decay</h4>
            <a
               href="https://www.urbandecay.com/vice-lipstick-by-urban-decay/ud771.html"
               className="btn btn-primary float-right btn-sm"
            >
               Buy Now
            </a>
            <h5 className="card-title">Light card title</h5>
            <p className="card-text" id="cardfontcolor">
               {" "}
               These are your personalized lip matches.The buy now buttons that
               are provided above will instantly take you to purchase your
               personalized lip color.You can save each look generated by
               pressing the save below.
            </p>
         </div>
         <div className="card bg-light mb-3" style={{ maxWidth: "18rem" }} />
         <div className="card-header">Match</div>
         <div className="card-body">
            <img
               src={appLogo}
               width="46px;"
               alt="Lip Service Lips"
               className="mb-1 ml-2"
            />
            <h4 id="cardfontcolor"> Name:Hitch Hike</h4>
            <h4 id="cardfontcolor"> Finish: Comfort Matte</h4>
            <h4 id="cardfontcolor"> Brand: Urban Decay</h4>
            <a
               href="https://www.urbandecay.com/vice-lipstick-by-urban-decay/ud771.html"
               className="btn btn-primary float-right btn-sm"
            >
               Buy Now
            </a>
            <h5 className="card-title">Light card title</h5>
            <p className="card-text" id="cardfontcolor">
               {" "}
               These are your personalized lip matches.The buy now buttons that
               are provided above will instantly take you to purchase your
               personalized lip color.You can save each look generated by
               pressing the save below.
            </p>
         </div>
         <div className="mb-8"></div>
         <div className="mb-8"></div>
         <Link
            to="/your-looks"
            className="btn btn-outline-primary btn-lg float-right"
            id="nextButton"
         >
            Save
         </Link>
         <Link
            to="/lip-service-quiz"
            className="btn btn-outline-primary btn-lg "
            id="nextButton"
         >
            Back
         </Link>
         <div className="mb-8"></div>
      </AppTemplate>
   );
}
